export enum ItemType {
  Unknown = 0,
  Head = 1,
  Chest = 2,
  Belt = 3,
  Legs = 4,
  Boots = 5,
  Necklace = 6,
  Ring = 7,
  Gadget = 8,
  Missiles = 9,
  Piercing = 10,
  SurpriseBox = 11,
  ShopTitle = 12,
  Reskill = 13,
  WeddingRing = 14,
  DivorceItem = 15,
}
