import { Gender, Locale } from '../../game/types';
import { CharacterInterface } from '../interfaces/character.interface';
import { StatType } from '../types';

export class CharacterModel {
  id: number;
  userId: number;
  name: string;
  locale: Locale;
  gender: Gender;
  sexuality: Gender;
  title: string;
  gameCurrency: number;
  xp: number;
  level: number;
  description: string;
  note: string;
  tsLastAction: number;
  onlineStatus: number;
  scoreHonor: number;
  scoreLevel: number;
  scoreFans: number;
  statPointsAvailable: number;
  statBaseStamina: number;
  statBaseStrength: number;
  statBaseCriticalRating: number;
  statBaseDodgeRating: number;
  statTotalStamina: number;
  statTotalStrength: number;
  statTotalCriticalRating: number;
  statTotalDodgeRating: number;
  statWeaponDamage: number;
  statTotal: number;
  statBoughtStamina: number;
  statBoughtStrength: number;
  statBoughtCriticalRating: number;
  statBoughtDodgeRating: number;
  activeQuestBoosterId: string;
  tsActiveQuestBoostExpires: number;
  activeStatsBoosterId: string;
  tsActiveStatsBoostExpires: number;
  activeWorkBoosterId: string;
  tsActiveWorkBoostExpires: number;
  tsActiveSenseBoostExpires: number;
  tsActiveMultitaskingBoostExpires: number;
  maxQuestStage: number;
  currentQuestStage: number;
  currentLocation: number;
  questEnergy: number;
  maxQuestEnergy: number;
  tsLastQuestEnergyRefill: number;
  questEnergyRefillAmountToday: number;
  activeQuestId: number;
  questPool: string;
  honor: number;
  tsLastDuel: number;
  activeDuelId: number;
  duelStamina: number;
  maxDuelStamina: number;
  tsLastDuelStaminaChange: number;
  duelStaminaCost: number;
  tsLastDuelEnemiesRefresh: number;
  currentWorkOfferId: string;
  tsLastWorkCollection: number;
  activeConventionShowId: number;
  tsDungeonKeyFound: number;
  activeDungeonQuestId: number;
  tsLastDungeonQuest: number;
  lastDungeonQuestLost: boolean;
  activeDungeonId: number;
  tsLastDungeonStarted: number;
  appearanceSkinColor: number;
  appearanceHairType: number;
  appearanceHairColor: number;
  appearanceHeadType: number;
  appearanceEyesType: number;
  appearanceEyebrowsType: number;
  appearanceEyebrowsColor: number;
  appearanceNoseType: number;
  appearanceMouthType: number;
  appearanceFacialHairType: number;
  appearanceFacialHairColor: number;
  appearanceDecorationType: number;
  showHeadItem: boolean;
  showChestItemUnlocked: boolean;
  showChestItem: boolean;
  showBeltItemUnlocked: boolean;
  showBeltItem: boolean;
  showLegsItemUnlocked: boolean;
  showLegsItem: boolean;
  showBootsItemUnlocked: boolean;
  showBootsItem: boolean;
  appearancePhotoRectType: number;
  appearancePhotoBorderType: number;
  appearancePhotoBackgroundType: number;
  appearancePhotoFilterType: number;
  appearancePhotoIconType: number;
  appearancePhotoSexualityType: number;
  appearanceTattooArmLeft: number;
  appearanceTattooArmRight: number;
  appearanceTattooBody: number;
  appearanceTattooLegLeft: number;
  appearanceTattooLegRight: number;
  appearanceBraType: number;
  appearancePantiesType: number;
  appearanceGenitalsType: number;
  appearanceGenitalsHairType: number;
  appearanceGenitalsHairColor: number;
  avatarImage: string;
  tutorialFlags: string;
  storygoal: string;
  guildId: number;
  guildRank: number;
  finishedGuildBattleAttackId: number;
  finishedGuildBattleDefenseId: number;
  guildDonatedGameCurrency: number;
  guildDonatedPremiumCurrency: number;
  guildCompetitionPointsGathered: number;
  pendingGuildCompetitionTournamentRewards: number;
  pendingSoloGuildCompetitionTournamentRewards: number;
  unreadMassSystemMessages: number;
  friendMessagesOnly: boolean;
  conventionId: number;
  conventionShowCount: number;
  conventionShowIdentifier: string;
  conventionShowReward: number;
  tsLastWashItem: number;
  tsLastDailyLoginBonus: number;
  dailyLoginBonusDay: number;
  pendingTournamentRewards: number;
  pendingGlobalTournamentRewards: number;
  tsLastShopRefresh: number;
  maxFreeShopRefreshes: number;
  shopRefreshes: number;
  movieEnergy: number;
  maxMovieEnergy: number;
  tsLastMovieEnergyChange: number;
  moviePool: string;
  movieId: number;
  movies: number;
  fans: number;
  tsLastMovieFinished: Date;
  moviesStartedToday: number;
  movieVotes: number;
  selectedMovieId: number;
  selectableMoviesCount: number;
  pendingMovieTournamentRewards: number;
  friendData: string;
  unusedResources: string;
  usedResources: string;
  battleData: string;
  tsLastCustomizeItem: number;
  pendingCustomizeItem: string;
  currentStoryDungeonIndex: number;
  activeStoryDungeonAttackId: number;
  currentRepeatStoryDungeonId: number;
  activeRepeatStoryDungeonAttackId: number;
  eventQuestId: number;
  drawEventId: number;
  currentEnergyStorage: number;
  currentSlotmachineSpin: number;
  slotmachineSpinCount: number;
  tsLastSlotmachineRefill: number;
  newUserVoucherIds: string;
  herobookObjectivesRenewedToday: number;
  userStoryActivated: boolean;
  userStoryLocales: string;
  activeSeasonProgressId: number;

  get hasStatPointsAvailable(): boolean {
    return this.statPointsAvailable > 0;
  }

  get statPoints(): { [statType in StatType]: number } {
    return {
      [StatType.Strength]: this.statTotalStrength,
      [StatType.Stamina]: this.statTotalStamina,
      [StatType.Critical]: this.statTotalCriticalRating,
      [StatType.Dodge]: this.statTotalDodgeRating,
    };
  }

  get statsTotal(): number {
    return [
      this.statTotalStrength,
      this.statTotalStamina,
      this.statTotalDodgeRating,
      this.statTotalCriticalRating,
      this.statWeaponDamage,
    ].reduce((sum, stat) => sum + stat, 0);
  }

  get canDuel(): boolean {
    return this.duelStamina >= this.duelStaminaCost;
  }

  constructor(character: CharacterInterface) {
    this.id = character.id;
    this.userId = character.user_id;
    this.name = character.name;
    this.locale = character.locale;
    this.gender = character.gender;
    this.sexuality = character.sexuality;
    this.title = character.title;
    this.gameCurrency = character.game_currency;
    this.xp = character.xp;
    this.level = character.level;
    this.description = character.description;
    this.note = character.note;
    this.tsLastAction = character.ts_last_action;
    this.onlineStatus = character.online_status;
    this.scoreHonor = character.score_honor;
    this.scoreLevel = character.score_level;
    this.scoreFans = character.score_fans;
    this.statPointsAvailable = character.stat_points_available;
    this.statBaseStamina = character.stat_base_stamina;
    this.statBaseStrength = character.stat_base_strength;
    this.statBaseCriticalRating = character.stat_base_critical_rating;
    this.statBaseDodgeRating = character.stat_base_dodge_rating;
    this.statTotalStamina = character.stat_total_stamina;
    this.statTotalStrength = character.stat_total_strength;
    this.statTotalCriticalRating = character.stat_total_critical_rating;
    this.statTotalDodgeRating = character.stat_total_dodge_rating;
    this.statWeaponDamage = character.stat_weapon_damage;
    this.statTotal = character.stat_total;
    this.statBoughtStamina = character.stat_bought_stamina;
    this.statBoughtStrength = character.stat_bought_strength;
    this.statBoughtCriticalRating = character.stat_bought_critical_rating;
    this.statBoughtDodgeRating = character.stat_bought_dodge_rating;
    this.activeQuestBoosterId = character.active_quest_booster_id;
    this.tsActiveQuestBoostExpires = character.ts_active_quest_boost_expires;
    this.activeStatsBoosterId = character.active_stats_booster_id;
    this.tsActiveStatsBoostExpires = character.ts_active_stats_boost_expires;
    this.activeWorkBoosterId = character.active_work_booster_id;
    this.tsActiveWorkBoostExpires = character.ts_active_work_boost_expires;
    this.tsActiveSenseBoostExpires = character.ts_active_sense_boost_expires;
    this.tsActiveMultitaskingBoostExpires = character.ts_active_multitasking_boost_expires;
    this.maxQuestStage = character.max_quest_stage;
    this.currentQuestStage = character.current_quest_stage;
    this.currentLocation = character.current_location;
    this.questEnergy = character.quest_energy;
    this.maxQuestEnergy = character.max_quest_energy;
    this.tsLastQuestEnergyRefill = character.ts_last_quest_energy_refill;
    this.questEnergyRefillAmountToday = character.quest_energy_refill_amount_today;
    this.activeQuestId = character.active_quest_id;
    this.questPool = character.quest_pool;
    this.honor = character.honor;
    this.tsLastDuel = character.ts_last_duel;
    this.activeDuelId = character.active_duel_id;
    this.duelStamina = character.duel_stamina;
    this.maxDuelStamina = character.max_duel_stamina;
    this.tsLastDuelStaminaChange = character.ts_last_duel_stamina_change;
    this.duelStaminaCost = character.duel_stamina_cost;
    this.tsLastDuelEnemiesRefresh = character.ts_last_duel_enemies_refresh;
    this.currentWorkOfferId = character.current_work_offer_id;
    this.tsLastWorkCollection = character.ts_last_work_collection;
    this.activeConventionShowId = character.active_convention_show_id;
    this.tsDungeonKeyFound = character.ts_dungeon_key_found;
    this.activeDungeonQuestId = character.active_dungeon_quest_id;
    this.tsLastDungeonQuest = character.ts_last_dungeon_quest;
    this.lastDungeonQuestLost = character.last_dungeon_quest_lost;
    this.activeDungeonId = character.active_dungeon_id;
    this.tsLastDungeonStarted = character.ts_last_dungeon_started;
    this.appearanceSkinColor = character.appearance_skin_color;
    this.appearanceHairType = character.appearance_hair_type;
    this.appearanceHairColor = character.appearance_hair_color;
    this.appearanceHeadType = character.appearance_head_type;
    this.appearanceEyesType = character.appearance_eyes_type;
    this.appearanceEyebrowsType = character.appearance_eyebrows_type;
    this.appearanceEyebrowsColor = character.appearance_eyebrows_color;
    this.appearanceNoseType = character.appearance_nose_type;
    this.appearanceMouthType = character.appearance_mouth_type;
    this.appearanceFacialHairType = character.appearance_facial_hair_type;
    this.appearanceFacialHairColor = character.appearance_facial_hair_color;
    this.appearanceDecorationType = character.appearance_decoration_type;
    this.showHeadItem = character.show_head_item;
    this.showChestItemUnlocked = character.show_chest_item_unlocked;
    this.showChestItem = character.show_chest_item;
    this.showBeltItemUnlocked = character.show_belt_item_unlocked;
    this.showBeltItem = character.show_belt_item;
    this.showLegsItemUnlocked = character.show_legs_item_unlocked;
    this.showLegsItem = character.show_legs_item;
    this.showBootsItemUnlocked = character.show_boots_item_unlocked;
    this.showBootsItem = character.show_boots_item;
    this.appearancePhotoRectType = character.appearance_photo_rect_type;
    this.appearancePhotoBorderType = character.appearance_photo_border_type;
    this.appearancePhotoBackgroundType = character.appearance_photo_background_type;
    this.appearancePhotoFilterType = character.appearance_photo_filter_type;
    this.appearancePhotoIconType = character.appearance_photo_icon_type;
    this.appearancePhotoSexualityType = character.appearance_photo_sexuality_type;
    this.appearanceTattooArmLeft = character.appearance_tattoo_arm_left;
    this.appearanceTattooArmRight = character.appearance_tattoo_arm_right;
    this.appearanceTattooBody = character.appearance_tattoo_body;
    this.appearanceTattooLegLeft = character.appearance_tattoo_leg_left;
    this.appearanceTattooLegRight = character.appearance_tattoo_leg_right;
    this.appearanceBraType = character.appearance_bra_type;
    this.appearancePantiesType = character.appearance_panties_type;
    this.appearanceGenitalsType = character.appearance_genitals_type;
    this.appearanceGenitalsHairType = character.appearance_genitals_hair_type;
    this.appearanceGenitalsHairColor = character.appearance_genitals_hair_color;
    this.avatarImage = character.avatar_image;
    this.tutorialFlags = character.tutorial_flags;
    this.storygoal = character.storygoal;
    this.guildId = character.guild_id;
    this.guildRank = character.guild_rank;
    this.finishedGuildBattleAttackId = character.finished_guild_battle_attack_id;
    this.finishedGuildBattleDefenseId = character.finished_guild_battle_defense_id;
    this.guildDonatedGameCurrency = character.guild_donated_game_currency;
    this.guildDonatedPremiumCurrency = character.guild_donated_premium_currency;
    this.guildCompetitionPointsGathered = character.guild_competition_points_gathered;
    this.pendingGuildCompetitionTournamentRewards =
      character.pending_guild_competition_tournament_rewards;
    this.pendingSoloGuildCompetitionTournamentRewards =
      character.pending_solo_guild_competition_tournament_rewards;
    this.unreadMassSystemMessages = character.unread_mass_system_messages;
    this.friendMessagesOnly = character.friend_messages_only;
    this.conventionId = character.convention_id;
    this.conventionShowCount = character.convention_show_count;
    this.conventionShowIdentifier = character.convention_show_identifier;
    this.conventionShowReward = character.convention_show_reward;
    this.tsLastWashItem = character.ts_last_wash_item;
    this.tsLastDailyLoginBonus = character.ts_last_daily_login_bonus;
    this.dailyLoginBonusDay = character.daily_login_bonus_day;
    this.pendingTournamentRewards = character.pending_tournament_rewards;
    this.pendingGlobalTournamentRewards = character.pending_global_tournament_rewards;
    this.tsLastShopRefresh = character.ts_last_shop_refresh;
    this.maxFreeShopRefreshes = character.max_free_shop_refreshes;
    this.shopRefreshes = character.shop_refreshes;
    this.movieEnergy = character.movie_energy;
    this.maxMovieEnergy = character.max_movie_energy;
    this.tsLastMovieEnergyChange = character.ts_last_movie_energy_change;
    this.moviePool = character.movie_pool;
    this.movieId = character.movie_id;
    this.movies = character.movies;
    this.fans = character.fans;
    this.tsLastMovieFinished = new Date(character.ts_last_movie_finished);
    this.moviesStartedToday = character.movies_started_today;
    this.movieVotes = character.movie_votes;
    this.selectedMovieId = character.selected_movie_id;
    this.selectableMoviesCount = character.selectable_movies_count;
    this.pendingMovieTournamentRewards = character.pending_movie_tournament_rewards;
    this.friendData = character.friend_data;
    this.unusedResources = character.unused_resources;
    this.usedResources = character.used_resources;
    this.battleData = character.battle_data;
    this.tsLastCustomizeItem = character.ts_last_customize_item;
    this.pendingCustomizeItem = character.pending_customize_item;
    this.currentStoryDungeonIndex = character.current_story_dungeon_index;
    this.activeStoryDungeonAttackId = character.active_story_dungeon_attack_id;
    this.currentRepeatStoryDungeonId = character.current_repeat_story_dungeon_id;
    this.activeRepeatStoryDungeonAttackId = character.active_repeat_story_dungeon_attack_id;
    this.eventQuestId = character.event_quest_id;
    this.drawEventId = character.draw_event_id;
    this.currentEnergyStorage = character.current_energy_storage;
    this.currentSlotmachineSpin = character.current_slotmachine_spin;
    this.slotmachineSpinCount = character.slotmachine_spin_count;
    this.tsLastSlotmachineRefill = character.ts_last_slotmachine_refill;
    this.newUserVoucherIds = character.new_user_voucher_ids;
    this.herobookObjectivesRenewedToday = character.herobook_objectives_renewed_today;
    this.userStoryActivated = character.user_story_activated;
    this.userStoryLocales = character.user_story_locales;
    this.activeSeasonProgressId = character.active_season_progress_id;
  }
}
